### PR TITLE
updated read me

### PR DESCRIPTION
**Pull request by royandroid63**

### CODE REVIEW

**Comment by HLBuilder** [comment]
Can one of the admins verify this patch?

**Comment by aldoherty73** [comment]
add to whitelist

**Comment by aldoherty73** [comment]
rerun tests

**Comment by aldoherty73** [comment]
Roy please check your code

**Comment by aldoherty73** [comment]
rerun tests

**Comment by aldoherty73** [comment]
rerubtests

**Comment by aldoherty73** [comment]
rerun tests

**Comment by aldoherty73** [comment]
rerun tests

**Comment by aldoherty73** [comment]
rerun tests

**Comment by aldoherty73** [comment]
Roy, Please tidy up your code

**Pull request closed without merging**
