### PR TITLE
testing 3rd Jul

### PR DESCRIPTION
**Pull request by AfshinGhahramani**
working i=on issue #28

### CODE REVIEW

**Comment by HLBuilder** [comment]
Can one of the admins verify this patch?

**Comment by HLBuilder** [comment]
Can one of the admins verify this patch?

**Comment by AfshinGhahramani** [comment]
retest please

**Comment by AfshinGhahramani** [comment]
run tests

**Comment by aldoherty73** [comment]
rerun tests

**Comment by aldoherty73** [comment]
run tests

**Comment by AfshinGhahramani** [comment]
run tests

**Comment by AfshinGhahramani** [comment]
run tests

**Comment by aldoherty73** [comment]
run tests

**Comment by AfshinGhahramani** [comment]
run tests

**Comment by AfshinGhahramani** [comment]
add to whitelist

**Comment by AfshinGhahramani** [comment]
resolves #29

**Pull request merged**
